[project]
name = "course-paper"
version = "0.1.0"
description = "Entropy and complexity analysis of respiratory sounds using Bandt-Pompe method"
readme = "README.md"
requires-python = ">=3.13"
authors = [
    {name = "Timur Toktamysov", email = "timur.toktamysov@gmail.com"}
]
dependencies = [
    "librosa>=0.10.2",
    "matplotlib>=3.9.0",
    "numpy>=2.4.0",
    "ordpy>=1.2.2",
    "scipy>=1.17.0",
]
